(defun root1 (a b c)
    (setq test (- (* b b) (* 4 a c)))
    (if (> test 0)
        (/ (- (- 0 b) (sqrt test)) (* 2 a))
        ()
    )
)

(defun root2 (a b c)
    (setq test (- (* b b) (* 4 a c)))
    (if (> test 0)
        (/ (+ (- 0 b) (sqrt test)) (* 2 a))
        ()
    )
)